# Generated by Django 5.2.17 on 2026-08-25 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoExigido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('instrucoes', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('triagem', 'Triagem'), ('coletando_documentos', 'Coletando documentos'), ('aguardando_analise', 'Aguardando análise'), ('aguardando_humano', 'Aguardando humano'), ('encerrada', 'Encerrada')], default='triagem', max_length=30)),
                ('modo', models.CharField(choices=[('bot', 'Bot'), ('humano', 'Humano')], default='bot', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.contato')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.servico')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, upload_to='atendimento/documentos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('motivo_reprovacao', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_recebidos', to='atendimento.conversa')),
                ('documento_exigido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.documentoexigido')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('conteudo', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='atendimento.conversa')),
            ],
        ),
        migrations.AddField(
            model_name='documentoexigido',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_exigidos', to='atendimento.servico'),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_atendimento', 'Em atendimento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('origem', models.CharField(choices=[('fluxo_completo', 'Fluxo completo'), ('pedido_atendente', 'Pedido de atendente')], max_length=20)),
                ('resumo_triagem', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('assumida_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.contato')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.conversa')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.servico')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-criada_em'], name='atendimento_status_d849fb_idx'), models.Index(fields=['contato'], name='atendimento_contato_6e7575_idx')],
            },
        ),
    ]
