# Generated by Django 5.2.17 on 2026-09-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_documentorecebido_analisado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
