# Generated by Django 5.2.17 on 2026-09-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_contato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='conversa',
            name='tentativas_invalidas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
