# Generated by Django 5.2.17 on 2026-09-18 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_contato_chat_id_conversa_tentativas_invalidas'),
        ('empresas', '0002_empresa_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='servico',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConfiguracaoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Desligado, toda mensagem nova vai direto para um atendente.')),
                ('saudacao', models.TextField(default='Olá! Sou o assistente virtual da {empresa}.', help_text='Primeira linha do menu. Use {empresa} para o nome da empresa.')),
                ('rotulo_atendente', models.CharField(default='Falar com um atendente', help_text='Texto da última opção do menu, que sempre chama um humano.', max_length=120)),
                ('mensagem_nao_entendi', models.TextField(default='Não entendi.', help_text='Vem antes do menu repetido quando a resposta não é uma opção válida.')),
                ('mensagem_transferencia', models.TextField(default='Vou chamar um atendente para falar com você por aqui. Só um momento.')),
                ('mensagem_conclusao', models.TextField(default='Recebi todos os documentos!\n\nUm atendente vai analisar e falar com você por aqui.', help_text='Enviada quando o cliente termina de mandar os documentos.')),
                ('max_tentativas_invalidas', models.PositiveSmallIntegerField(default=3, help_text='Respostas seguidas não entendidas antes de transferir para um atendente.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('palavras_atendente', models.CharField(default='atendente, humano, pessoa', help_text='Separadas por vírgula. Em qualquer etapa, transferem para um atendente.', max_length=255)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_bot', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'configuração do chatbot',
                'verbose_name_plural': 'configurações do chatbot',
            },
        ),
    ]
