# Generated by Django 5.2.17 on 2026-09-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_alter_servico_options_servico_ordem_configuracaobot'),
        ('empresas', '0002_empresa_padrao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servico',
            name='servico_empresa_nome_unico',
        ),
        migrations.AddField(
            model_name='servico',
            name='mensagem_apos_escolha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='pai',
            field=models.ForeignKey(blank=True, help_text='Opção da qual esta é uma sub-opção. Vazio = opção do menu principal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subopcoes', to='atendimento.servico'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(condition=models.Q(('pai__isnull', True)), fields=('empresa', 'nome'), name='servico_empresa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(condition=models.Q(('pai__isnull', False)), fields=('empresa', 'pai', 'nome'), name='servico_empresa_pai_nome_unico'),
        ),
    ]
