# Generated by Django 5.2.17 on 2026-09-18 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def marcar_saidas_antigas_como_bot(apps, schema_editor):
    """O default do campo é 'cliente', o que estaria errado para todo o
    histórico de saída — antes desta migration, quem falava era só o bot."""
    Mensagem = apps.get_model('atendimento', 'Mensagem')
    Mensagem.objects.filter(direcao='saida').update(origem='bot')


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_remove_servico_servico_empresa_nome_unico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['criada_em']},
        ),
        migrations.AddField(
            model_name='configuracaobot',
            name='horas_ate_expirar',
            field=models.PositiveSmallIntegerField(default=48, help_text='Horas de silêncio até a conversa ser encerrada e voltar ao bot. Atendimento já assumido por alguém nunca expira.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='origem',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('bot', 'Bot'), ('atendente', 'Atendente'), ('celular', 'Celular da empresa')], default='cliente', max_length=12),
        ),
        migrations.RunPython(
            marcar_saidas_antigas_como_bot, migrations.RunPython.noop),
    ]
