# Generated by Django 5.2.17 on 2026-09-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0008_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['criada_em', 'id']},
        ),
    ]
