# Generated by Django 5.2.17 on 2026-08-29 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0003_documentorecebido_analisado_em_and_more'),
        ('empresas', '0002_empresa_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='WahaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sessao', models.CharField(max_length=100, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=128)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_waha', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'sessão WAHA',
                'verbose_name_plural': 'sessões WAHA',
            },
        ),
        migrations.CreateModel(
            name='EventoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem.recebida', 'Mensagem recebida'), ('mensagem.enviada', 'Mensagem enviada'), ('conversa.estado_alterado', 'Estado da conversa alterado'), ('documento.recebido', 'Documento recebido'), ('documento.analisado', 'Documento analisado'), ('documento.revisado', 'Documento revisado'), ('tarefa.criada', 'Tarefa criada'), ('webhook.recebido', 'Webhook recebido'), ('erro', 'Erro')], max_length=40)),
                ('ator', models.CharField(default='sistema', max_length=50)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='atendimento.conversa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_atendimento', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', '-criado_em'], name='integracao__empresa_a7f0ea_idx'), models.Index(fields=['tipo', '-criado_em'], name='integracao__tipo_b0e634_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('waha', 'WAHA'), ('meta', 'Meta'), ('n8n', 'n8n')], max_length=20)),
                ('id_externo', models.CharField(max_length=200)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks_recebidos', to='empresas.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['origem', 'id_externo'], name='integracao__origem_7121a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('origem', 'id_externo', 'empresa'), name='webhook_idempotente_por_empresa')],
            },
        ),
    ]
