# Generated by Django 5.2.17 on 2026-09-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wahasessao',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Desconhecido'), ('STOPPED', 'Parada'), ('STARTING', 'Iniciando'), ('SCAN_QR_CODE', 'Aguardando leitura do QR Code'), ('WORKING', 'Conectada'), ('FAILED', 'Falhou')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='wahasessao',
            name='status_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
