# Generated by Django 5.2.17 on 2026-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao', '0002_wahasessao_status_wahasessao_status_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoatendimento',
            name='tipo',
            field=models.CharField(choices=[('mensagem.recebida', 'Mensagem recebida'), ('mensagem.enviada', 'Mensagem enviada'), ('conversa.estado_alterado', 'Estado da conversa alterado'), ('documento.recebido', 'Documento recebido'), ('documento.analisado', 'Documento analisado'), ('documento.revisado', 'Documento revisado'), ('tarefa.criada', 'Tarefa criada'), ('tarefa.atribuida', 'Tarefa atribuída'), ('webhook.recebido', 'Webhook recebido'), ('erro', 'Erro')], max_length=40),
        ),
    ]
