# Generated by Django 5.2.17 on 2026-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao', '0003_alter_eventoatendimento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wahasessao',
            name='tentativas_recuperacao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
