# Generated by Django 5.2 on 2026-08-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('administrador', 'Administrador'), ('atendente', 'Atendente'), ('operador_documentos', 'Operador de documentos')], default='atendente', max_length=24)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuário da empresa',
                'verbose_name_plural': 'usuários da empresa',
            },
        ),
        migrations.AddConstraint(
            model_name='empresausuario',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario'), name='empresa_usuario_unico'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['usuario', 'ativo'], name='empresas_em_usuario_eb62a7_idx'),
        ),
        migrations.AddIndex(
            model_name='empresausuario',
            index=models.Index(fields=['empresa', 'ativo'], name='empresas_em_empresa_8c6eaa_idx'),
        ),
    ]
