# Generated by Django 5.2.15 on 2026-07-02 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='PDF')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='processando', max_length=12)),
                ('erro', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, db_index=True, max_length=7)),
                ('placa_valida', models.BooleanField(default=False, verbose_name='placa válida')),
                ('renavam', models.CharField(blank=True, max_length=14)),
                ('proprietario', models.CharField(blank=True, max_length=120, verbose_name='proprietário')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
