# Generated by Django 5.2.15 on 2026-07-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_pipeline_openai'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
